build: false
platform:
  - x32
  - x64

clone_folder: "C:\\HT"

environment:
  global:
    node_version: "7"

branches:
  except:
    - "gh-pages"

init:
  - IF NOT EXIST C:\T mkdir C:\T
  - SET TEMP=C:\T
  - SET TMP=C:\T

install:
  - ps: Install-Product node $env:node_version
  - npm install -g electron-forge
  - yarn install


test_script:
  - node --version
  - yarn --version
  - yarn lint
  - SET DEBUG=*
  - yarn make

before_deploy:
  - yarn make
  - appveyor PushArtifact out\make\HitTracker-win32-%PLATFORM%-%APPVEYOR_REPO_TAG_NAME%.exe

deploy:
    description: "Release $(APPVEYOR_REPO_TAG_NAME)"
    provider: GitHub
    auth_token:
      secure: "N7AGr+WKRHnBh8dscxot6kPvACQt1AY5HIQ1UVqAaiV/dPlKPQiCLy8JNiW17KMx"
    artifact: /.*\.exe/
    draft: true
    prerelease: false
    on:
        branch: master
        appveyor_repo_tag: true
cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"
  - '%USERPROFILE%\.electron'
