build: false
platform:
  - x64

clone_folder: "C:\\HT"

environment:
  global:
    GITHUB_TOKEN:
      secure: 9va/uJFLZdZhq9AUQif1Txb9nSaAcLzcWvSC20I6B7KdV6xXzAujIMGouU2zqQAW
    node_version: "10"

branches:
  except:
    - "gh-pages"

init:
  - IF NOT EXIST C:\T mkdir C:\T
  # the default TEMP/TMP paths are too long for electron-windows-installer to package them
  - SET TEMP=C:\T
  - SET TMP=C:\T
  - SET NODE_ARCH=%PLATFORM%
  - IF %PLATFORM% == x86 SET NODE_ARCH=ia32

install:
  - ps: Install-Product node $env:node_version $env:PLATFORM
  - npm install -g electron-forge
  - npm install


test_script:
  - node --version
  - npm --version
  - npm lint


deploy_script:
  - IF NOT "%APPVEYOR_REPO_TAG_NAME%" == "" npm forge-publish --arch=%NODE_ARCH%

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
