build: false
platform:
  - x86
  - x64

clone_folder: "C:\\HT"

environment:
  global:
    GITHUB_TOKEN:
      secure: 9va/uJFLZdZhq9AUQif1Txb9nSaAcLzcWvSC20I6B7KdV6xXzAujIMGouU2zqQAW
    node_version: "7"

branches:
  except:
    - "gh-pages"

init:
  - IF NOT EXIST C:\T mkdir C:\T
  # the default TEMP/TMP paths are too long for electron-windows-installer to package them
  - SET TEMP=C:\T
  - SET TMP=C:\T

install:
  - ps: Install-Product node $env:node_version $env:PLATFORM
  - npm install -g electron-forge
  - yarn install


test_script:
  - node --version
  - yarn --version
  - yarn lint


deploy_script:
  - IF NOT "%APPVEYOR_REPO_TAG_NAME%" = "" yarn make
  - IF NOT "%APPVEYOR_REPO_TAG_NAME%" = "" yarn publish

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"
  - '%USERPROFILE%\.electron'
