platform:
  - x32
  - x64

environment:
  global:
    - node_version: "7"

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
    - "gh-pages"

install:
  - ps: Install-Product node $env:node_version
  - yarn install


build_script:
  - yarn run build

test_script:
  - node --version
  - yarn --version
  - yarn run test
  - yarn run e2e

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"
  - '%USERPROFILE%\.electron'
