build: false
platform:
  - x64

clone_folder: "C:\\HT"

environment:
  global:
    GITHUB_TOKEN:
      secure: 9va/uJFLZdZhq9AUQif1Txb9nSaAcLzcWvSC20I6B7KdV6xXzAujIMGouU2zqQAW
    node_version: '12.4.0'

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/

init:
  - IF NOT EXIST C:\T mkdir C:\T
  # the default TEMP/TMP paths are too long for electron-windows-installer to package them
  - SET TEMP=C:\T
  - SET TMP=C:\T
  - SET NODE_ARCH=%PLATFORM%
  - IF %PLATFORM% == x86 SET NODE_ARCH=ia32
  - SET DEBUG=electron-rebuild

install:
  - ps: Install-Product node $env:node_version $env:PLATFORM
  - SET PATH=%APPDATA%\npm;%PATH%
  - npm ci

test_script:
  - node --version
  - npm --version
  - npm run lint
  - if %APPVEYOR_REPO_TAG% EQU false npm run forge-make

build_script:
  - IF %APPVEYOR_REPO_TAG% EQU true  npm run forge-publish --arch=%NODE_ARCH%

cache:
  #- node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
