sudo: false
dist: trusty

os:
  - linux
#  - osx

language: node_js
node_js:
  - 8.9.3

addons:
  apt:
    packages:
      - build-essential
      - icnsutils
      - graphicsmagick
      - libudev-dev
      # for node-printer
      - libcups2-dev
      - libgnome-keyring-dev
      - xz-utils

env:
  global:
    - secure: "UhyALjaKu795IhUd+sB3sTYEiXx4eYghyQeqB8MNfXXjKf0Ot1wo0/7PSeqryYYyxj2etqBndJG1jDaR4NSd3UaNb00ljJCkzOrI+4ipBwinmUhaOKHYiSNJKk2CUC0MRDe9Qhn2v8HR0vQAJAt7hXhpy+29ADuXOtmK4NZatRTMAdkb0djgRLaQ9Y3yH0oauWy7TI9vEocGWniyOOrgalEXkVvODxpc0kQR1JqTLCGfyzavAA2DtIoUpth6taFW3wPJ69oNSRdsijlRX+hRv7RCSPHzeBrD7mjhRnYHjzrff7m1tgEiWGxp8fuU4QuxBOYK/++U2YV5IqOcGS88riOqT0JL6neCMU0DqJwU8X5DUBvGV5pOfsmRgI85nk/cRaqJIoXQAjK2u1ewhUfsDYAgfB7dNJ111f04pBBmduanSYF7i91Tx9DI7f9b2H8iNwUGLdPhwefzQWdFHAC24QFEnG/0lqtXjcwEnYDRe+YBUyPtme3bpcGz2pe4+LsaP1b+Gg+ZJ0lPzj9++JAc1egsdQrHC4/xNwfkDHPgzJR+gtGI7f4JzM3jD4a+GXZ8yrw6n/JL5ZldYVGJPS4Phnvdcg9Ci/uejAmosVpDbDpL5CEJTFXBMpiqTSbffNy/ng6TrAjFh+r8tA93flpdtsya0KIggS76PbJIlnqnRpQ="

before_install:
  - export NODE_PLATFORM=linux
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export NODE_PLATFORM=darwin; fi

install:
  - npm install -g npm@6
  - npm install -g electron-forge
  - npm install
script:
  - npm --version
  - node --version
  - npm run lint
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
  #- npm test
  #- npm run e2e

after_success:
  -  if [[ "${TRAVIS_TAG}" != "" ]]; then npm run forge-publish; fi

cache:
  npm: true
  directories:
    - node_modules

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
    - gh-pages
