sudo: false
dist: trusty

os:
  - linux
  - osx

language: node_js
node_js:
  - 7.5.0

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - libgnome-keyring-dev
      - xz-utils

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
    - yarn install
    - yarn test
    - yarn run e2e

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
