sudo: false
dist: trusty

os:
  - linux
#  - osx

language: node_js
node_js:
  - 7.7.1

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      # for node-printer
      - libcups2-dev
      - libgnome-keyring-dev
      - xz-utils

install:
    # manually install yarn until https://github.com/travis-ci/travis-ci/issues/7454 is fixed
    - npm install -g yarn
    - npm install -g electron-forge
    - yarn install
script:
    - yarn --version
    - node --version
    - yarn lint
    - yarn make
    #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
    #- yarn test
    #- yarn run e2e

before_deploy:
    - yarn make

deploy:
    provider: releases
    api_key:
        secure: "LJ1ZwqBmg6GajDkgtFrgkNttfmBObPAAUPnJr8d53mXEA6+ZwZw/fIXOt7BzOQOow2DWMDf+PAqMkmSQLwdjnRB+jGIa4yJHnOQ1BxgyLuiQ5yiFckkHwBt+1HrKGZ54uxaQBej1/wbBi1GrEhz5BNWjAsHotGVMbiJ6dR4uU24="
    file: "out/make/*"
    file_glob: true
    skip_cleanup: true
    on:
        tags: true
cache:
  yarn: true
  npm: true
  directories:
    - node_modules

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
