sudo: false
dist: trusty

os:
  - linux
#  - osx

language: node_js
node_js:
  - 7.7.4

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      # for node-printer
      - libcups2-dev
      - libgnome-keyring-dev
      - xz-utils

before_install:
  - export NODE_PLATFORM=linux
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export NODE_PLATFORM=darwin; fi

install:
  # manually install yarn until https://github.com/travis-ci/travis-ci/issues/7454 is fixed
  - npm install -g yarn
  - npm install -g electron-forge
  - yarn install
script:
  - yarn --version
  - node --version
  - yarn lint
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
  #- yarn test
  #- yarn run e2e

before_deploy:
  - yarn make
  - mv out/make/HitTracker-$NODE_PLATFORM-x64.zip out/make/HitTracker-$NODE_PLATFORM-x64-$TRAVIS_TAG.zip

deploy:
  provider: releases
  api_key:
    secure: D+awB144WTyUv9Qh8ecyLFowiymc5QQZN7z8/dTmILEx7IiNGztb2eZ8kO3U/JSnT3YlOeEgg4sWrua82mUzgTVrC94r73T0fzdNVgAIqzP5GgBDJLLIyMX3aVZ6FcDQK95mZy5UMS8xSdXuWse6PSuSfkO56OgVokHxeJFgIaeQdcwjgx4/zaJ+vUuu5SS56mdoxQY1vM96GPANQGNEjAvwXspal2mDr40C5vyz1iv348myQknzB6yQ5x7ZRnR7kN0EMt5EZG1k0wFxyxBjTadaBM4T11doSSJmIOqKdpoYudFodzf99ri4a9AqTRKK2A99nY+752zTiPULFCRt3L00jFkv+sOuSLz5b2htKWvDVZzRaGQ30a4gDK1L+iSlTKE8rA8D55sDQxam/j+MP3N+b2MRPcqGmG1uc0k2Z5NO9X+PEMvKy7CWt5qweZK4DpFTXHKYxdEt9PSPZ0IF1HF5+CBYtMRfOZrZaiqB6qZsNBdb3dSt9nSSe0wJ7yDdo78Vyz4TBKgnjwhQ7BKlsOrSnbtdXXFY1AUwm9kBVWvEqODNnkZZcAhBmGQpAJ9VzWjly+kvXt06WbGDTs3OnrcJRCn4WDemFKFcGHKRBe7gwN/5sRdWtB9/m7BoEXms6xL/5Iz/TLCa7F0u+vGeOh1troqIwnJkkYUPSTPytNE=
  file: "out/make/*"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
cache:
  yarn: true
  npm: true
  directories:
    - node_modules

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
    - gh-pages
