/** Declaration file generated by dts-gen */

export = xdg_basedir;

declare const xdg_basedir: {
    cache: string;
    config: string;
    configDirs: string[];
    data: string;
    dataDirs: string[];
    runtime: string;
};
